print("About My Family")
print("A Nuclear Family of 4 members")
print("My Dad Mr.L.Ganesan")
print("My Mom Mrs.S.Venmathi")
print("I have a little Sister, she is Dhivya Soundarya")
print()
print("About My Friends")
print("Sona")
print("Girija")
print("JayaShree")
print("Amirtha")
print("Abirami")