print("X,XII Mark")
print()
print("X Mark: 440")
print("English: 85")
print("Tamil: 99")
print("Mathematics: 75")
print("Science: 89")
print("Social Science: 92")
print("----------------------------------------")
print("XII Mark: 460")
print("English: 99")
print("Mathematics: 84")
print("Physics: 91")
print("Chemistry: 94")
print("Computer Science: 88")
