print("Create a Tuple")
t=()
l=list(t)
num=int(input("Enter number of elements: "))
for i in range(num):
    e=int(input("Enter an element: "))
    l.append(e)
t = tuple(l)
print(t)
print()
print("Finding the size of the tuple")
print(l)
print(len(l))
print()
print("Sorting tuples")
sorted_tuple=sorted(t)
print("Sorted Tuple: ",sorted_tuple)
print()
print("Create a tuple with different data types")
tup=()
li=list(t)
num=int(input("Enter number of elements: "))
for i in range(num):
    el=input("Enter an element: ")
    li.append(el)
tup = tuple(li)
print(tup)
print()
print("Unpack a tuple into several variables")
tup1=1,2,3
a,b,c=tup1
print("a: ",a)
print("b: ",b)
print("c: ",c)
print()
print("Converting a tuple to a string")
print(tup)
print(str(tup))
print()
print("Get the 4th element and 4th element from last of a tuple")
t1=(10,20,30,40,50,60,70,80)
print("4th element: ",t1[3])
print("4th element from last: ",t1[-4])
print()
print("Finding Repeated items in a tuple")
duplicates=[]
for i in t1:
    if t1.count(i) > 1 and i not in duplicates:
        duplicates.append(i)
print("Repeated items: ",duplicates)
print()
print("To Check whether an element exists or not")
t2=(34,56,23,25,81)
x=int(input("Enter element to check: "))
if x in t2:
    print(x,"exists in the tuple")
else:
    print(x,"doesn't exist in the tuple")
print()
print("Convert a list to a tuple")
lis=[1,2,3,4]
print(lis)
print(tuple(lis))
print()
print("Remove an item from a tuple")
tup2=(1,2,3,4,5)
li5=list(tup2)
li5.remove(3)
tup2=tuple(li5)
print("Tuple after Removing 4th element: ",tup2)
print()
print("Slicing a tuple")
print(tup2)
print("First Two Elements: ",tup2[:2])
print("Last Two Elements: ",tup2[-2:])
print()
print("Finding the index of an item in a tuple")
tup3=(5,10,15,20,25)
print("Index of 15 is: ",tup3.index(15))
print()
print("Finding the Length of Tuple")
print(tup3)
print(len(tup3))
print()
print("Reversing a Tuple")
print(tup2)
print("Reversed Tuple: ",tup[::-1])
print()
print("Converting a given string list to a tuple")
list2=['Almond','Cake','Berries','Dragon Fruit']
print(tuple(list2))
